name: Build and Deploy

on:
  push:
    branches: 
      - feature/ci
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install-Build-Deploy 🚀
        run: |
          npm ci
          npm run predeploy
          npm run deploy